# Generated by Django 5.1 on 2024-09-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image', verbose_name='Product Name'),
            preserve_default=False,
        ),
    ]
