# Generated by Django 5.1 on 2024-09-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0006_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdetails',
            field=models.CharField(max_length=2000, verbose_name='Product Details'),
        ),
    ]
