# Generated by Django 5.1 on 2024-09-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0009_remove_billingaddress_oid_billingaddress_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
