# Generated by Django 5.1 on 2024-09-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0011_billingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
