# Generated by Django 5.1 on 2024-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0015_coverimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title Of Tips')),
                ('desc', models.TextField(verbose_name='Tips Description')),
                ('category', models.CharField(choices=[('Hair Care Tips', 'Hair Care Tips'), ('Skin Care Tips', 'Skin Care Tips'), ('Makeup Tips', 'Makeup Tips')], max_length=200, verbose_name='Category')),
            ],
        ),
    ]
