# Generated by Django 5.1 on 2024-09-22 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0016_beautytips'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautytips',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
