# Generated by Django 5.1 on 2024-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0017_beautytips_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautytips',
            name='image',
            field=models.ImageField(default='image/beauty1.jpg', upload_to='image', verbose_name='Image'),
        ),
    ]
