# Generated by Django 5.1 on 2024-09-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0018_beautytips_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='first name')),
                ('lname', models.CharField(max_length=200, verbose_name='last name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('msg', models.TextField(verbose_name='message')),
                ('mob', models.CharField(max_length=200, verbose_name='Mobile number')),
            ],
        ),
    ]
