# Generated by Django 5.1 on 2024-10-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_app', '0022_address_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offvalue',
            field=models.IntegerField(default=0, verbose_name='% OFF on Price'),
        ),
    ]
